[package]
name = "markdown-countdown-lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
tower-lsp = "0.20.0"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"

# For parsing and time logic
chrono = "0.4"
chrono-humanize = "0.2"
regex = "1"
once_cell = "1.18" # For lazy static regex compilation
dashmap = "6.1.0"
tracing-appender = "0.2.3"
